### ISSUE TITLE
AttributeError: module 'hashlib' has no attribute 'file_digest'

### ISSUE THREAD

**Issue by ngrlt** [WAUthethird/quixel-megascans-scripts#2]
Hi,

First off, many thanks for your work on this neat tool !

After claiming all the assets following another method, I tried to download the assets using your script but I receive an error after the first asset has finished downloading. Here is a screenshot of the terminal window.

![Screenshot_2024-10-13_at_10 18 50@2x](https://github.com/user-attachments/assets/2a2b7e3e-d7dd-4c32-8ea3-230f90783d2c)

I first tried using the asset-metadata.json that you provided and then I generated one myself, but in either case I receive the same error message. I have no clue where the problem might come from...

Thanks for your help

**Comment by WAUthethird** [comment]
Hi! That's definitely a odd error, considering hashlib comes with Python. Are you using Python 3.12 or above? hashlib.file_digest was added in 3.11, and I use the features added to f-strings in 3.12.

**Comment by ngrlt** [comment]
Hi, many thanks for your quick reply. Actually you were totally right I just forgot to check the version of python beforehand... I was running 3.9... I updated to 3.12 and it works flawlessly ! Thanks again for this amazing set of scripts !

**Comment by WAUthethird** [comment]
Awesome! Glad I could help.
